name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/eggs
          key: ${{ runner.os }}-eggs-${{ matrix.python-version }}-${{ hashFiles('*cfg') }}
          restore-keys: |
            ${{ runner.os }}-eggs-${{ matrix.python-version }}-
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.python-version }}
